swagger: '2.0'
info:
  description: Credit card Service to create and Retrieve Credit card Details
  version: 1.0.0
  title: Credit Card service API
host: 'localhost:8082'
basePath: /
tags:
  - name: credit-card-controller
    description: This API provides the capability to Store and Retrieve credit card Details
paths:
  /credit-card:
    get:
      tags:
        - credit-card-controller
      summary: Retrieve list of Credit Card details
      operationId: getCreditDetailsUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: Successfully retrieved list
          schema:
            type: array
            items:
              $ref: '#/definitions/CardDetails'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - credit-card-controller
      summary: Created Credit Card Details
      operationId: createCreditDetailsUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: cardDetails
          description: cardDetails
          required: true
          schema:
            $ref: '#/definitions/CardDetails'
      responses:
        '201':
          description: Created Credit Card Details
          schema:
            $ref: '#/definitions/CardDetails'
        '400':
          description: Unable to Create Credit Card Details
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  CardDetails:
    type: object
    properties:
      balance:
        type: number
        format: double
      cardNo:
        type: string
        minLength: 0
        maxLength: 19
        pattern: '^(0|[1-9][0-9]*)$'
      id:
        type: string
      limit:
        type: string
      name:
        type: string
    title: CardDetails
